### ISSUE TITLE
Keyboard columns or rows

### ISSUE THREAD

**Issue by JeffOdegard** [hashcat/kwprocessor#24]
The most popular keyboard walk out there is some form of 1qaz2wsx3edc4rfv.  As written, it doesn't look like kwp can produce keymaps where you look at the columns or rows, e.g. you jump from the end of one column to the beginning of the next.

**Comment by jsteube** [comment]
In theory yes, you just need to allow a jump a gap that big. But that would end up in poor efficiency. 

That's why, by purpose, this is not supported. Instead use hashcat in -a 1 attack mode with a wordlist produced from kwp to cover stuff like 1qaz2wsx3edc4rfv. You might want to preprocess them with combinator.bin to have multiple pattern covered.
